---
version: "3"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: nextcloud
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    volumes:
      - db:/var/lib/postgresql/data
    labels:
      - docker-volume-backup.stop-during-backup=true 
  nextcloud:
    image: nextcloud
    restart: always
    ports:
      - 8080:80
    links:
      - db
    volumes:
      - nextcloud:/var/www/html
    labels:
      - docker-volume-backup.stop-during-backup=true
    environment:
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST=db
  backup:
    image: offen/docker-volume-backup:latest
    env_file: ./backup.env
    volumes:
      - nextcloud:/backup/nextcloud-backup:ro
      - db:/backup/postgres-backup:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /home/alex/nextcloud/backup:/archive    
volumes:
  nextcloud:
  db:
